CREATE TABLE shopCart(
sessionId CHAR(100) NOT NULL PRIMARY KEY,
userInfoId INTEGER,
userName VARCHAR(100),
createDate DATE,
lastAcessDate DATE,
clientIP CHAR(100),
totalPrice DECIMAL(10,2)
);


CREATE TABLE SHOPCARTPRODUCTITEM(
PRODUCTITEMID INTEGER NOT NULL IDENTITY PRIMARY KEY,
SESSIONID CHAR(100) NOT NULL ,
PRODUCTID INTEGER NOT NULL,
PRODUCTNAME VARCHAR(100),
PRICE DECIMAL(10,2),
ORDERQUANTITY INTEGER,
DESCRIPTION LONGVARCHAR,
WEIGHT DECIMAL(10,2),
URL  VARCHAR(100),
IMAGEID INTEGER,
IMGPATH  VARCHAR(100) 
);