<script language="javascript" src="jquery/jquery-1.2.6.js"></script>
<script language="javascript" src="jquery/jquery.form.js"></script>
<script language="javascript" src="jquery/jquery.validate.js"></script>
<script language="javascript" src="jquery/localization"></script>
<script language="javascript" src="jquery/effects.blind.js"></script>
<script language="javascript" src="jquery/effects.bounce.js"></script>
<script language="javascript" src="jquery/effects.clip.js"></script>
<script language="javascript" src="jquery/effects.core.js"></script>
<script language="javascript" src="jquery/effects.drop.js"></script>
<script language="javascript" src="jquery/effects.explode.js"></script>
<script language="javascript" src="jquery/effects.fold.js"></script>
<script language="javascript" src="jquery/effects.highlight.js"></script>
<script language="javascript" src="jquery/effects.pulsate.js"></script>
<script language="javascript" src="jquery/effects.scale.js"></script>
<script language="javascript" src="jquery/effects.shake.js"></script>
<script language="javascript" src="jquery/effects.slide.js"></script>
<script language="javascript" src="jquery/effects.transfer.js"></script>
<script language="javascript" src="jquery/ui.accordion.js"></script>
<script language="javascript" src="jquery/ui.core.js"></script>
<script language="javascript" src="jquery/ui.datepicker.js"></script>
<script language="javascript" src="jquery/ui.dialog.js"></script>
<script language="javascript" src="jquery/ui.draggable.js"></script>
<script language="javascript" src="jquery/ui.droppable.js"></script>
<script language="javascript" src="jquery/ui.resizable.js"></script>
<script language="javascript" src="jquery/ui.selectable.js"></script>
<script language="javascript" src="jquery/ui.slider.js"></script>
<script language="javascript" src="jquery/ui.sortable.js"></script>
<script language="javascript" src="jquery/ui.tabs.js"></script>
