-- Light Portal drop tables

drop table if exists light_address_book
drop table if exists light_blog
drop table if exists light_blog_comment
drop table if exists light_bookmark
drop table if exists light_bulletin
drop table if exists light_calendar
drop table if exists light_calendar_event
drop table if exists light_calendar_holiday
drop table if exists light_category_ad
drop table if exists light_category_ad_comment
drop table if exists light_channel_ref
drop table if exists light_chat
drop table if exists light_chat_buddy
drop table if exists light_chat_status_ref
drop table if exists light_chatting
drop table if exists light_chatting_record
drop table if exists light_feedback
drop table if exists light_flash_game
drop table if exists light_forum
drop table if exists light_forum_category
drop table if exists light_forum_post
drop table if exists light_friend_request
drop table if exists light_group
drop table if exists light_group_bulletin
drop table if exists light_group_category
drop table if exists light_group_forum
drop table if exists light_group_picture
drop table if exists light_horoscope
drop table if exists light_horoscope_weekly
drop table if exists light_internal_news
drop table if exists light_message
drop table if exists light_not_keyword
drop table if exists light_not_word
drop table if exists light_note
drop table if exists light_org_profile
drop table if exists light_organization
drop table if exists light_popular_item
drop table if exists light_popular_item_comment
drop table if exists light_portal
drop table if exists light_portal_tab
drop table if exists light_portlet
drop table if exists light_portlet_preferences
drop table if exists light_portlet_ref
drop table if exists light_recommended_item
drop table if exists light_role
drop table if exists light_store
drop table if exists light_store_catalog
drop table if exists light_store_order
drop table if exists light_store_order_item
drop table if exists light_store_product
drop table if exists light_store_shipping_address
drop table if exists light_store_shoppingcart
drop table if exists light_todo
drop table if exists light_user
drop table if exists light_user_block
drop table if exists light_user_comment
drop table if exists light_user_favourite
drop table if exists light_user_file
drop table if exists light_user_group
drop table if exists light_user_invite
drop table if exists light_user_keyword
drop table if exists light_user_music
drop table if exists light_user_picture
drop table if exists light_user_picture_rank
drop table if exists light_user_profile
drop table if exists light_user_role
drop table if exists light_viewed_item
drop table if exists light_viewed_item_user